"use client";
import { useCallback, useState } from "react";
import Image from "next/image";
import { motion, useReducedMotion } from "framer-motion";
import { galleryItems } from "@/data/gallery";
import { externalLinks } from "@/config/site";
import { ExternalLinkButton } from "./external-link-button";
import { ImageModal } from "./image-modal";

export function GallerySection(){const [selected,setSelected]=useState<(typeof galleryItems)[number]|null>(null);const close=useCallback(()=>setSelected(null),[]);const reduce=useReducedMotion();return <MotionGallery><div className="container"><div className="mb-12 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">02 · Selected works</p><h2 className="section-title">Gallery</h2></div><p className="max-w-md text-sm leading-relaxed text-zinc-500">Fragments of Kiri’s universe — six moments suspended between dreams and distant stars.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{galleryItems.map((item,i)=><motion.button key={item.src} onClick={()=>setSelected(item)} whileHover={reduce?{}:{y:-6,scale:1.012}} transition={{duration:.22}} className="group relative aspect-[4/5] overflow-hidden rounded-2xl border border-white/10 bg-zinc-900 text-left shadow-2xl shadow-black/20" aria-label={`查看大图：${item.label}`}><Image src={item.src} alt={item.alt} fill sizes="(max-width:640px) 100vw,(max-width:1024px) 50vw,33vw" className="object-cover transition duration-500 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/5 to-transparent"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-5"><div><span className="text-[10px] tracking-[.2em] text-violet-300">0{i+1}</span><h3 className="mt-1 font-[family-name:var(--font-display)] text-xl">{item.label}</h3></div><span className="text-xs text-white/50">EXPAND ↗</span></div></motion.button>)}</div><div className="mt-12 text-center"><ExternalLinkButton href={externalLinks.fantia} variant="ghost">View More on Fantia</ExternalLinkButton></div></div><ImageModal item={selected} onClose={close}/></MotionGallery>}
function MotionGallery({children}:{children:React.ReactNode}){return <section id="gallery" className="section bg-[#0c0c11]">{children}</section>}
